#!/bin/bash
# m h  dom mon dow   command
# 0 1  *   *   *     /home/ulf/src/userinterface/src/scripts/cronjob

BASE=$(dirname $0)
BASE=$(readlink -f $BASE)

SS=/home/ulf/heizung/gz
DD=/home/ulf/public_html/heizung/bilder

mkdir -p $DD

doit()
{
set -x
cd $DD
$BASE/plotday $SS/

cd $SS
for f in *.log_*
do
  # DS in YYMMDD
  DS=$(echo $f | cut -d '_' -f2)
  DS="../arch/${DS:0:2}/${DS:2:2}/${DS:4:2}"
  mkdir -p $DS
  mv $f $DS
done
}

doit >>~/tmp/cronjob.log 2>&1
