#!/bin/bash

BASE=$(dirname $0)
BASE=$(readlink -f $BASE)

SS=/home/ulf/src/Heizung/workspace/regelung/run/log
DD=/home/ulf/src/Heizung/workspace/regelung/bilder/

doit()
{
cd $DD
$BASE/plottoday $SS
rsync -av ./ vdr:public_html/heizung/bilder/
}

doit >>~/tmp/cronjob.log 2>&1
