#!/bin/bash

BASE=$(dirname $0)
BASE=$(readlink -f $BASE)

SS=/home/ulf/src/Heizung/workspace/regelung/run
DD=/home/ulf/src/Heizung/ws_js/userInterface/src/scripts/bilder

doit()
{
cd $DD
$BASE/plotday $SS/gz $SS
cp -l 20*/*.png ~/backup/bilder
cd $SS
gzip -v *
mv *.gz gz
}

doit >>~/tmp/cronjob.log 2>&1
