#!/bin/bash
# m h  dom mon dow   command
# 0 1  *   *   *     crontab

BASE=$(dirname $0)
BASE=$(readlink -f $BASE)

SS=/home/ulf/heizung/gz
DD=/home/ulf/public_html/heizung/bilder

mkdir -p $DD

doit()
{
set -x
cd $DD
$BASE/plotday $SS/

cd $SS
for f in *.log_*
do
  DS=$(echo $f | cut -d '_' -f2)
  mkdir -p ../arch/$DS
  mv $f ../arch/$DS
done
}

doit >>~/tmp/cronjob.log 2>&1
