#!/bin/bash

# $1 Sensor

#if [ "$1" = "" ]
#then
#  echo "usage: $0 sensor"
#  ls ~/sensors
#  exit 1
#fi

S="BrauchWasser FussbodenVorlauf FussbodenRuecklauf ZentralVorlauf PufferOben PufferMitte"

cd ~/tmp/temp_verlauf/

while true
do 
  D=$(date +"%Y%m%d")
  [ -d "$D" ] || mkdir "$D"
  (
    cd "$D"
    H=$(date +"%H:%M:%S")
    echo $H
    for s in $S
    do
      MW="$(< ~/sensors/$s/temperature)"
      printf "   %-20s %5.1f\n" $s $MW
      echo $H $MW >> $s.dat
    done
  )
  sleep 15
done
