#!/bin/bash

S="$@"
#D=${2:-} # Datum im Format 2013-Feb-23
BASE=$(dirname $0)
BASE=$(readlink -f $BASE)

. $BASE/jullib.sh

# simple tool for making zcat tolerant
mycat()
{
  for f
  do
    if [ ${f%.gz} = $f ]
    then
      #echo "cat $f" >/dev/tty
      cat $f
    else
      #echo "zcat $f" >/dev/tty
      zcat $f
    fi
  done
}

# reads files from stdin and writes the content of that file to stdout
# if filename ends in .gz decompress before
tocat()
{
  while read f
  do
    if [ ${f%.gz} = $f ]
    then
      #echo "cat $f" >/dev/tty
      cat $f
    else
      #echo "zcat $f" >/dev/tty
      zcat $f
    fi
  done
}

if [ "$D" = "" ]
then
  # gestriges Datum ermitteln
   J=$(dat2jul $(date +"%Y %m %d"))
   #let J=J-1
   set -- $(jul2dat $J)
   D=$(date -d"$1-$2-$3" +"%Y-%m-%d")
   DP=$(date -d"$1-$2-$3" +"%Y-%b-%d")
fi

DDir=$(echo $D | tr '-' '/')
rm -rf $DDir
mkdir -p $DDir

echo "getting measure points"

# QuerySensorsThread.log_*
# processEvent 2017-Apr-18 21:38:31 : ZentralVorlauf=50

#mycat $S/EnetService.log_* | fgrep $D | $BASE/plotprep
#find $S -name "EnetService.log_*" | sort | tocat | fgrep $D | tee save | $BASE/plotprep
for f in $S
do
  ls $f/QuerySensorsThread.log_*
done | tocat | fgrep $DP | $BASE/plotprep

echo "plotting"
echo "  in $DDir"
cd $DDir

cat $BASE/verlauf.gplot | gawk -v date=$D '
  // { gsub("{d}", date); print; }' | gnuplot

echo "done"

