#!/bin/bash

S=$1
BASE=$(dirname $0)
BASE=$(readlink -f $BASE)
FNAME=QuerySensorsThread

if false
then
  echo "getting dates"
  DIRS=$(zcat $S/$FNAME.log_*.gz | $BASE/plotprep.datum | sort -u)

  echo "found $DIRS"
  for d in $DIRS
  do
    mkdir -p $d
  done

  echo "getting measure points"

  zcat $S/$FNAME.log_*.gz | $BASE/plotprep
fi

echo "plotting"
for d in *-*-*
do
  echo "  in $d"
  cd $d
  cat $BASE/verlauf.gplot | gawk -v date=$d '
  // { gsub("{d}", date); print; }' | gnuplot
  cd -
done

echo "done"
